### ISSUE TITLE
增加日志

### ISSUE THREAD

**Issue by IceFire-X** [feiyangbeyond/halo-theme-sagiri#11]
提个小建议，作者阔以参考下hanshan的日志，集成到sagiri主题来

**Comment by feiyangbeyond** [comment]
嗯，借鉴过寒山日志页面的展示形式，但是我感觉不怎么搭，因为 sagiri 还有一个悬浮的侧边栏。
现在一直也没什么好的想法，还在搁置

**Comment by feiyangbeyond** [comment]
#3
