### ISSUE TITLE
markdown编辑后的展示效果和页面展示效果不一致

### ISSUE THREAD

**Issue by nbzm7** [feiyangbeyond/halo-theme-sagiri#13]
![image](https://user-images.githubusercontent.com/33958623/83321715-0dda1400-a284-11ea-9035-2a8312f018b4.png)
![image](https://user-images.githubusercontent.com/33958623/83321722-1894a900-a284-11ea-8a02-4265209bb42f.png)
一图是编辑文章页面，蓝色字体，到了展示页面后就变成了浅灰色。这样使我看不清自己文字有超链接。

我试图修改了main.css中3445行的a{color:#FF6A6A}, 保存之后我发现在页面定位到链接时，color还是原来的十六进制代码

**Comment by feiyangbeyond** [comment]
> ![image](https://user-images.githubusercontent.com/33958623/83321715-0dda1400-a284-11ea-9035-2a8312f018b4.png)
> ![image](https://user-images.githubusercontent.com/33958623/83321722-1894a900-a284-11ea-8a02-4265209bb42f.png)
> 一图是编辑文章页面，蓝色字体，到了展示页面后就变成了浅灰色。这样使我看不清自己文字有超链接。
> 
> 我试图修改了main.css中3445行的a{color:#FF6A6A}, 保存之后我发现在页面定位到链接时，color还是原来的十六进制代码



































> ![image](https://user-images.githubusercontent.com/33958623/83321715-0dda1400-a284-11ea-9035-2a8312f018b4.png)
> ![image](https://user-images.githubusercontent.com/33958623/83321722-1894a900-a284-11ea-8a02-4265209bb42f.png)
> 一图是编辑文章页面，蓝色字体，到了展示页面后就变成了浅灰色。这样使我看不清自己文字有超链接。
> 
> 我试图修改了main.css中3445行的a{color:#FF6A6A}, 保存之后我发现在页面定位到链接时，color还是原来的十六进制代码

如果你要修改文章的超链接样式，可以在博客后台 -> 主题 ->  Sagiri -> 设置 -> 博客设置 -> 最下面的自定义样式加入以下代码：
```css
.post-block a{
    color: #409EFF;
}
```

颜色可以自行修改。

也可以在后台 -> 系统 -> 博客设置 -> 其他设置 -> 自定义全局 head 中加入以下代码：
```css
<style type="text/css"> 
.post-block a{
    color: #409EFF;
}
</style> 
```
颜色可根据自己的需求自行更改

**Comment by nbzm7** [comment]
> > ![image](https://user-images.githubusercontent.com/33958623/83321715-0dda1400-a284-11ea-9035-2a8312f018b4.png)
> > ![image](https://user-images.githubusercontent.com/33958623/83321722-1894a900-a284-11ea-8a02-4265209bb42f.png)
> > 一图是编辑文章页面，蓝色字体，到了展示页面后就变成了浅灰色。这样使我看不清自己文字有超链接。
> > 我试图修改了main.css中3445行的a{color:#FF6A6A}, 保存之后我发现在页面定位到链接时，color还是原来的十六进制代码
> 
> > ![image](https://user-images.githubusercontent.com/33958623/83321715-0dda1400-a284-11ea-9035-2a8312f018b4.png)
> > ![image](https://user-images.githubusercontent.com/33958623/83321722-1894a900-a284-11ea-8a02-4265209bb42f.png)
> > 一图是编辑文章页面，蓝色字体，到了展示页面后就变成了浅灰色。这样使我看不清自己文字有超链接。
> > 我试图修改了main.css中3445行的a{color:#FF6A6A}, 保存之后我发现在页面定位到链接时，color还是原来的十六进制代码
> 
> 如果你要修改文章的超链接样式，可以在博客后台 -> 主题 -> Sagiri -> 设置 -> 博客设置 -> 最下面的自定义样式加入以下代码：
> 
> ```css
> .post-block a{
>     color: #409EFF;
> }
> ```
> 
> 颜色可以自行修改。
> 
> 也可以在后台 -> 系统 -> 博客设置 -> 其他设置 -> 自定义全局 head 中加入以下代码：
> 
> ```css
> <style type="text/css"> 
> .post-block a{
>     color: #409EFF;
> }
> </style> 
> ```
> 
> 颜色可根据自己的需求自行更改

谢谢你的回复

**Comment by feiyangbeyond** [comment]
> > > ![image](https://user-images.githubusercontent.com/33958623/83321715-0dda1400-a284-11ea-9035-2a8312f018b4.png)
> > > ![image](https://user-images.githubusercontent.com/33958623/83321722-1894a900-a284-11ea-8a02-4265209bb42f.png)
> > > 一图是编辑文章页面，蓝色字体，到了展示页面后就变成了浅灰色。这样使我看不清自己文字有超链接。
> > > 我试图修改了main.css中3445行的a{color:#FF6A6A}, 保存之后我发现在页面定位到链接时，color还是原来的十六进制代码
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/33958623/83321715-0dda1400-a284-11ea-9035-2a8312f018b4.png)
> > > ![image](https://user-images.githubusercontent.com/33958623/83321722-1894a900-a284-11ea-8a02-4265209bb42f.png)
> > > 一图是编辑文章页面，蓝色字体，到了展示页面后就变成了浅灰色。这样使我看不清自己文字有超链接。
> > > 我试图修改了main.css中3445行的a{color:#FF6A6A}, 保存之后我发现在页面定位到链接时，color还是原来的十六进制代码
> > 
> > 
> > 如果你要修改文章的超链接样式，可以在博客后台 -> 主题 -> Sagiri -> 设置 -> 博客设置 -> 最下面的自定义样式加入以下代码：
> > ```css
> > .post-block a{
> >     color: #409EFF;
> > }
> > ```
> > 
> > 
> > 颜色可以自行修改。
> > 也可以在后台 -> 系统 -> 博客设置 -> 其他设置 -> 自定义全局 head 中加入以下代码：
> > ```css
> > <style type="text/css"> 
> > .post-block a{
> >     color: #409EFF;
> > }
> > </style> 
> > ```
> > 
> > 
> > 颜色可根据自己的需求自行更改
> 
> 谢谢你的回复

感谢你的认可！
