### ISSUE TITLE
主题头像设置问题

### ISSUE THREAD

**Issue by zhangbaiquan** [feiyangbeyond/halo-theme-sagiri#18]
![Snipaste_2021-03-09_16-57-36](https://user-images.githubusercontent.com/22684684/110445152-cdec6b00-80f8-11eb-8984-590530001a2b.png)
![Snipaste_2021-03-09_17-00-14](https://user-images.githubusercontent.com/22684684/110445311-eeb4c080-80f8-11eb-862f-8e2d3ac44201.png)
你好，非常喜欢您的主题，感谢你的开源贡献，我的博客再设置上图的头像时，“这里通过后台 用户-个人资料-个人说明 来设置”
但是我这里后台设置时是一个文本框，我输出图片链接和markdown 链接都无效！
多谢

**Comment by feiyangbeyond** [comment]
![image](https://user-images.githubusercontent.com/43309682/110447079-d47be200-80fa-11eb-9301-b35395d70b06.png)

设置头像地方在这里, 个人说明里的内容会显示在首页头像(如你图示)下方

**Comment by zhangbaiquan** [comment]
谢谢，解决了，是我理解错误了
