### ISSUE TITLE
长文章目录无法显示完全

### ISSUE THREAD

**Issue by shakuameji** [feiyangbeyond/halo-theme-sagiri#23]
![图片](https://user-images.githubusercontent.com/88926614/130225487-3086461b-5460-4efe-8a69-62f03a4577f6.png)

如图，当文章目录因分级过多而过长时，无法显示完整目录。
或许可以给文章目录加一个滚动轴？（小声

**Comment by cetr** [comment]
你好，刚试了鼠标放在超长的目录上可以滚动呀

**Comment by cetr** [comment]
目测你用的火狐浏览器，刚又在火狐上试了下确实有问题

**Comment by shakuameji** [comment]
是的，火狐浏览器。
十分抱歉，我的问题描述错了。刚才尝试增多目录，可以滚动访问。

问题如下：
![图片](https://user-images.githubusercontent.com/88926614/130242700-b1ecc5d3-0f1a-4540-863b-9bc8045e3adf.png)
拉到页面底端时无法展示   单个一级菜单下的所有次级菜单  比如图中的 1-3-2、1-3-3、1-3-4...

**Comment by cetr** [comment]
但是侧栏贴底了，一会儿我会发布个版本完善一下

**Comment by shakuameji** [comment]
好的，十分感谢，辛苦您了！
