### ISSUE TITLE
关于500 Internal Server Error

### ISSUE THREAD

**Issue by Grouse-1** [feiyangbeyond/halo-theme-sagiri#26]
小白一个，主题非常喜欢，但不知道为什么手机端一访问就出现500 Internal Server Error，然后网站就没了，最后只能重新(docker容器)部署halo才弄好，但装上主题又会出现这种问题；

**Comment by cetr** [comment]
请提供更多信息以便我确定问题，比如，截图，日志，站点链接

**Comment by Grouse-1** [comment]
非常抱歉，刚才把那个主题删了，现在有装上手机端发现又好了，报错图片可能找不到了，我先用着，等报错了把信息发给你，浏览器历史记录只有如下搜索信息org.springframework.web.util.NestedServletException: Request processing fail...



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月5日(星期六) 晚上6:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cetr/halo-theme-sagiri] 关于500 Internal Server Error (Issue #26)





 
请提供更多信息以便我确定问题，比如，截图，日志，站点链接
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cetr** [comment]
好的，有问题再提issues就好
