### ISSUE TITLE
你好请问主题播放器设置自动播放没 效果。

### ISSUE THREAD

**Issue by nanjunyu** [feiyangbeyond/halo-theme-sagiri#27]
你好，谢谢作者的halo主题分享。
你好请问主题播放器开启了自动播放，但是还是没有自动播放是为什么。

**Comment by nanjunyu** [comment]
已经解决，谷歌浏览器设置一下声音允许就行了。
<img width="655" alt="image" src="https://user-images.githubusercontent.com/23097168/158010050-6c8e56de-4e83-41f3-a0f3-803b0e13b32e.png">

**Comment by cetr** [comment]
嗯好，然后提醒一下，手机上的话大多数移动端浏览器是禁止音频自动播放的

**Comment by cetr** [comment]
刚才看了下，是因为现在多数浏览器不允许自动播放，也不太建议开启，影响用户体验

**Comment by pythonxiaozhang** [comment]
> 

问一下楼主 知道怎么上传自己喜欢的音乐吗
