### ISSUE TITLE
关于怎么上传自己喜欢的音乐

### ISSUE THREAD

**Issue by pythonxiaozhang** [feiyangbeyond/halo-theme-sagiri#29]
首先感谢大佬分享自己的主题 非常感觉 。  然后就是想自己上传一些喜欢的音乐 是在哪个地方设置啊

**Comment by cetr** [comment]
首先要在主流音乐平台创建歌单
比如网易云，然后在网页上网易云音乐官网 music.163.com 打开自己主页找到歌单
歌单浏览器地址 `https://music.163.com/#/playlist?id=123456` ，把后面的数字 12456 填入 halo 后台主题设置里面
音乐播放器播放源选择网易云，歌单id填你歌单id，类似上面的123456

**Comment by cetr** [comment]
目前只做了网站左下角的播放器，而且只能通过第三方音乐平台的歌单，暂时不能自定义添加自己上传的音乐

**Comment by pythonxiaozhang** [comment]
可以自定义添加自己上传的音乐的 我已经搞定了 哈哈哈  音乐播放器歌单ID：改成自己歌单的ID就可以了
