### ISSUE TITLE
代码高亮怎么设置呢

### ISSUE THREAD

**Issue by clarke1999** [feiyangbeyond/halo-theme-sagiri#30]

**Comment by cetr** [comment]
需要主动指定语言类型，比如:

![image](https://user-images.githubusercontent.com/49756728/179397508-ac42691b-47d4-40c1-9eb1-2880bc0e9a0c.png)

**Comment by clarke1999** [comment]
感谢大佬！，你回复的好快呀


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cetr/halo-theme-sagiri"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 晚上8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cetr/halo-theme-sagiri] 代码高亮怎么设置呢 (Issue #30)





 
需要主动指定语言类型，比如:
