### ISSUE TITLE
主页文章显示的时候，会暴露出CSS代码，怎么才能去掉？

### ISSUE THREAD

**Issue by Hellokid** [feiyangbeyond/halo-theme-sagiri#31]
![image](https://user-images.githubusercontent.com/15140219/190889661-b0b9f7cc-d7ed-4277-a33a-685d8e02dbc9.png)

**Comment by cetr** [comment]
文章编辑器里怎么写的，应该是你文章格式不规范导致的

**Comment by Hellokid** [comment]
因为我想让段落首行空两字，插入的图片一样宽。我就这样写的：
<style>
     p{
text-indent: 2em;
}
img {
width: 800px;
}
</style>
下面就是正文，XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX。
这样导致了文章摘要截取150字的时候就自动把CSS代码截取上了，但是可以手动删除，每次这样太麻烦了。
另一方面，阅读全文的时候就不会显示出代码。我想应该是能够自动实现的，可我不会。
在文章页加的css样式也不是全能实现，比如给body加个背景色就实现不了，加了！import;也不行，不过打开页面的时候会闪一下那个背景色，不知道为什么。

**Comment by cetr** [comment]
css样式放文章最后面应该能暂时解决，这是后端这么设计的，和主题无关

**Comment by cetr** [comment]
我开始以为文章全文有异常，这个摘要可以在发布文章是手动修改

**Comment by Hellokid** [comment]
谢谢，太喜欢这个主题了。
