### ISSUE TITLE
在手机端首页标题显示异常

### ISSUE THREAD

**Issue by lxy914** [feiyangbeyond/halo-theme-sagiri#8]
![image](https://user-images.githubusercontent.com/41626157/80162114-f8c6f100-8604-11ea-8458-f2542c62d439.png)
字少的话正常显示，字一多就挤到一块了

**Comment by feiyangbeyond** [comment]
建议这里的字数不要太长，主题设置里可以自定义

**Comment by feiyangbeyond** [comment]
感觉多行就不好看了，一行显示很简练，你觉得呢？

**Comment by lxy914** [comment]
是的，一行就挺好，我减少标题字数了

**Comment by feiyangbeyond** [comment]
> 是的，一行就挺好，我减少标题字数了

好的
